### PR TITLE
import is not used

### PR DESCRIPTION
**Pull request by viniciussanchez**

### CODE REVIEW

**Comment by viniciussanchez** [comment]
Before this error occurred: 
image

With the tweaks and using python in version 3.10.1
image

Python version:
image

**Review by fgsl — CHANGES_REQUESTED** [review]
I agree with the removal of imports, because they are not used. In fact, they are tracks from the real consumer.
But the name of function is not related to this issue and there is not functional reason to change it. Keep the name.
Don't forget to rebase the code, because I will change the README and the comments of this file, to let clear that version of Python is 3.
Thank you for the contributions.

**Comment by viniciussanchez** [comment]
@fgsl Adjusted. I'm reading your book... it's pretty good so far. Function name was changed by VSCode sonarlint

**Review by fgsl — APPROVED** [review]

**Review by fgsl — APPROVED** [review]

**Review by fgsl — APPROVED** [review]

**Comment by fgsl** [comment]
> @fgsl Adjusted. I'm reading your book... it's pretty good so far. Function name was changed by VSCode sonarlint

Great! Thank you very much.

**Pull request merged**
